version: '2'
services:
  TEMPLATE_NAME_HOST:
    build: .
    environment:
      - ENV_NAME=local
      - NODE_ENV=production
      - PORT=8080
      - BASE_URL=http://TEMPLATE_NAME_HOST:8080
      - LOG_LEVEL=debug
      - VIRTUAL_HOST=dev.TEMPLATE_NAME_HOST,www.dev.TEMPLATE_NAME_HOST
      - VIRTUAL_PORT=8080
    ports:
      - '8080:8080'
